(let (my-keys
		 ((( "C-c C-c") 'comment-region)
		 (( "C-c C-u") 'uncomment-region)
		 (( "C-c C-r") 'replace-string)
		 (( "C-c p") 'goto-line)
		 (( "C-c C-b") 'search-forward-regexp)
		 (( "C-c d") 'svn-file-show-svn-diff)
		 (( "C-c s") 'google-search-selection)
		 (( "C-c g") 'google-it)
		 (( "C-c y") 'youtube-search)
		 (( "C-c u") 'my-browse-url)
		 (( "C-c f") 'grep)
		 (( "C-c d") 'recursive-grep)
		 (( "C-c c") 'compile)
		 (( "C-c j") 'jad)))
  (map (lambda (x)
	   (global-set-key (kbd (car x)) (cadr x))) my-keys))
